### ISSUE TITLE
Set Time for converted task

### ISSUE THREAD

**Issue by NC-MXTC** [SebastianHV/NCTaskManager#1]
https://github.com/SebastianHV/NCTaskManager/blob/15dfa710358bc791e2a5cc6d5b98a19934d053b9/src/main/java/mx/edu/j2se/hernandez/tasks/Tasks.java#L60

The time is never set for a converted task.

**Comment by SebastianHV** [comment]
Time set for both repetitive and non-repetitive tasks.
