### ISSUE TITLE
Repetition

### ISSUE THREAD

**Issue by NC-MXTC** [SebastianHV/NCTaskManager#2]
https://github.com/SebastianHV/NCTaskManager/blob/82cece2b58870b420da41369a128c0e2fe76ca45/src/main/java/mx/edu/j2se/hernandez/tasks/ArrayTaskList.java#L40

Why don't you use Tasks#nextTimeAfter ???

**Comment by SebastianHV** [comment]
Code corrected using the Tasks#nextTimeAfter method.
